bash prepare_label_no_spk_fckmeans.sh 1 6 "/nobackup/users/junruin2/data/hubert/libri-train-clean/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_1024/km_dir_1024/seg_feats/km_model_cpy.npy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/km_idx_FC_1_clsattnbndkmeans_from_1024" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model_FC_1_from_1024_cpy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model_cpy.npy" 4096


# bash prepare_label_no_spk_fckmeans.sh 1 6 "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_2048/km_dir_2048/seg_feats/km_model_cpy.npy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_idx_FC_1" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model_FC_1" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model_cpy.npy" 4096


# bash prepare_label_no_spk_fckmeans.sh 1 6 "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_2048/km_dir_2048/seg_feats/km_model_cpy.npy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gradseg_wav2bnd_bnd/top_4096/km_dir_4096/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gradseg_wav2bnd_bnd/top_4096/km_dir_4096/seg_feats/km_idx_FC_1" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model_FC_1_cpy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model_cpy.npy" 4096


# bash prepare_label_no_spk_fckmeans.sh 1 6 "/nobackup/users/junruin2/data/hubert/libri-train-clean/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_1024/km_dir_1024/seg_feats/km_model_cpy.npy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_2048/km_dir_2048/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_2048/km_dir_2048/seg_feats/km_idx_FC_1" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_2048/km_dir_2048/seg_feats/km_model_FC_1" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_2048/km_dir_2048/seg_feats/km_model_cpy.npy" 2048

# bash prepare_label_no_spk_fckmeans.sh 1 6 "/nobackup/users/junruin2/data/hubert/libri-train-clean/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_1024/km_dir_1024/seg_feats/km_model_cpy.npy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_gradseg_wav2bnd_bnd/top_2048/km_dir_2048/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_gradseg_wav2bnd_bnd/top_2048/km_dir_2048/seg_feats/km_idx_FC_1" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_2048/km_dir_2048/seg_feats/km_model_FC_1_cpy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_2048/km_dir_2048/seg_feats/km_model_cpy.npy" 2048


# bash prepare_label_no_spk_fckmeans.sh 1 6 "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_2048/km_dir_2048/seg_feats/km_model.npy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/km_idx_FC_1" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/km_model_FC_1" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/km_model.npy" 4096


# bash prepare_label_no_spk_fckmeans.sh 1 6 "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_2048/km_dir_2048/seg_feats/km_model_cpy.npy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/km_idx_FC_1_clsattnbndkmeans" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model_FC_1_cpy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model_cpy.npy" 4096



# bash prepare_label_no_spk_fckmeans.sh 1 6 "/nobackup/users/junruin2/data/hubert/libri-train-clean/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_1024/km_dir_1024/seg_feats/km_model.npy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/km_idx_FC_1_from_1024" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/km_model_FC_1_from_1024" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/km_model.npy" 4096


# bash prepare_label_no_spk_fckmeans.sh 1 6 "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_2048/km_dir_2048/seg_feats/km_model_cpy.npy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gradseg_wav2bnd_from_2048_e2e_w2b_large_no_opt/top_4096/km_dir_4096/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gradseg_wav2bnd_from_2048_e2e_w2b_large_no_opt/top_4096/km_dir_4096/seg_feats/km_idx_FC_1_from_2048" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model_FC_1_cpy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model_cpy.npy" 4096

bash prepare_label_no_spk_fckmeans.sh 1 6 "/nobackup/users/junruin2/data/hubert/libri-train-clean/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_1024/km_dir_1024/seg_feats/km_model_cpy.npy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/km_idx_FC_1_clsattnbndkmeans_from_1024" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model_FC_1_from_1024_cpy" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model_cpy.npy" 4096

