# bash prepare_label_no_spk.sh 1 6 "/nobackup/users/junruin2/LibriSpeech/tsv" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_idx" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model" "/nobackup/users/junruin2/hubert_base_ls960.pt" 4096

# bash prepare_label_no_spk.sh 1 6 "/nobackup/users/junruin2/LibriSpeech/tsv" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/km_idx" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/km_model" "/nobackup/users/junruin2/hubert_base_ls960.pt" 4096

# bash prepare_label_no_spk.sh 1 6 "/nobackup/users/junruin2/LibriSpeech/tsv" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_2048/km_dir_2048/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_2048/km_dir_2048/seg_feats/km_idx_clsattnbndkmeans" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-2048/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_2048/km_dir_2048/seg_feats/km_model_cpy" "/nobackup/users/junruin2/hubert_base_ls960.pt" 2048

# bash prepare_label_no_spk.sh 1 6 "/nobackup/users/junruin2/LibriSpeech/tsv" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gt_bnd/top_4096/km_dir_4096/seg_feats/km_idx_clsattnbndkmeans" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model_cpy" "/nobackup/users/junruin2/hubert_base_ls960.pt" 4096

# bash prepare_label_no_spk.sh 1 6 "/nobackup/users/junruin2/LibriSpeech/tsv" "/nobackup/users/junruin2/data/hubert/libri-train-clean/feat_hubert_large_l21_ori_feats_no_sil_wav2bnd_encoder_only_e2e_text_other_500_w2b_init_from_1e-3_model_2e-4lr/top_1024/km_dir_1024/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean/feat_hubert_large_l21_ori_feats_no_sil_wav2bnd_encoder_only_e2e_text_other_500_w2b_init_from_1e-3_model_2e-4lr/top_1024/km_dir_1024/seg_feats/km_idx_clsattnbndkmeans" "/nobackup/users/junruin2/data/hubert/libri-train-clean/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_1024/km_dir_1024/seg_feats/km_model_cpy" "/nobackup/users/junruin2/hubert_base_ls960.pt" 1024

# bash prepare_label_no_spk.sh 1 6 "/nobackup/users/junruin2/LibriSpeech/tsv" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gradseg_wav2bnd_diff_bnd_w2b_bnd/top_4096/km_dir_4096/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_gradseg_wav2bnd_diff_bnd_w2b_bnd/top_4096/km_dir_4096/seg_feats/km_idx_clsattnbndkmeans" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_4096/seg_feats/km_model_cpy" "/nobackup/users/junruin2/hubert_base_ls960.pt" 4096


# bash prepare_label_no_spk.sh 1 6 "/nobackup/users/junruin2/LibriSpeech/tsv" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_8192/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_8192/seg_feats/km_idx" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_8192/seg_feats/km_model" "/nobackup/users/junruin2/hubert_base_ls960.pt" 8192

# bash prepare_label_no_spk.sh 1 6 "/nobackup/users/junruin2/LibriSpeech/tsv" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_16384/seg_feats/" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_16384/seg_feats/km_idx" "/nobackup/users/junruin2/data/hubert/libri-train-clean-top-4096/feat_hubert_large_l21_ori_feats_no_sil_clsattn_bnd/top_4096/km_dir_16384/seg_feats/km_model" "/nobackup/users/junruin2/hubert_base_ls960.pt" 16384
